version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/run/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/run/staticfiles
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  static_volume: