# Generated by Django 4.2 on 2023-04-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('bdate', models.DateField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('size_of_tshirt', models.CharField(max_length=100, null=True)),
                ('with_dog', models.BooleanField(max_length=100, null=True)),
                ('dog_name', models.CharField(max_length=100, null=True)),
                ('dog_breed', models.CharField(max_length=100, null=True)),
                ('dog_bdate', models.DateField(null=True)),
                ('dog_adopt', models.BooleanField(max_length=100, null=True)),
            ],
        ),
    ]
