# Generated by Django 4.2 on 2023-04-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='bdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='dog_adopt',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='dog_bdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='with_dog',
            field=models.BooleanField(null=True),
        ),
    ]
