# Generated by Django 4.2 on 2023-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_peoples_sex_alter_peoples_bdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='sick',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='peoples',
            name='sick_text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
