# Generated by Django 4.2 on 2023-09-10 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_peoples_sick_peoples_sick_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peoples',
            name='time_to_go',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
